update

diff --git a/bin/cbmgr b/bin/cbmgr
--- a/bin/cbmgr
+++ b/bin/cbmgr
@@ -4,13 +4,13 @@ set -u
 
 if [ $# -eq 0 ]; then
     cat 1>&2 << _EOT_
-cbmgr.sh is a clipboard manager script for CLI environment of UNIX like system.
+cbmgr is a clipboard manager script for CLI environment of UNIX like system.
 Please run "clpmgr.sh --help" to show the usage of this command.
 _EOT_
     exit 1
 elif [ "$1" = "--help" ]; then
     cat << _EOT_
-usage: cbmgr.sh [--help] <command>
+usage: cbmgr [--help] <command>
 
 [option]
 --help
@@ -34,7 +34,7 @@ elif [ "$1" = "input" ] || [ "$1" = "i" ]; then
     elif command -v pbcopy > /dev/null 2>&1; then
         pbcopy
     else
-        printf "ERROR: at least a command of \"xclip\" or \"xsel\" or \"pbcopy\" is necessary.\\n" 1>&2
+        printf "ERROR: command \"xclip\", \"xsel\" or \"pbcopy\" not found.\\n" 1>&2
         exit 1
     fi
 elif [ "$1" = "output" ] || [ "$1" = "o" ]; then
@@ -45,7 +45,7 @@ elif [ "$1" = "output" ] || [ "$1" = "o" ]; then
     elif command -v pbpaste > /dev/null 2>&1; then
         pbpaste
     else
-        printf "ERROR: at least a command of \"xclip\" or \"xsel\" or \"pbpaste\" is necessary.\\n" 1>&2
+        printf "ERROR: command \"xclip\", \"xsel\" or \"pbcopy\" not found.\\n" 1>&2
         exit 1
     fi
 elif [ "$1" = "clear" ] || [ "$1" = "c" ]; then
@@ -56,7 +56,7 @@ elif [ "$1" = "clear" ] || [ "$1" = "c" ]; then
     elif command -v pbcopy > /dev/null 2>&1; then
         : | pbcopy
     else
-        printf "ERROR: at least a command of \"xclip\" or \"xsel\" or \"pbcopy\" is necessary.\\n" 1>&2
+        printf "ERROR: command \"xclip\", \"xsel\" or \"pbcopy\" not found.\\n" 1>&2
         exit 1
     fi
 else
