fixed the structure of the directory

diff --git a/bin/dotutil b/bin/dotutil
--- a/bin/dotutil
+++ b/bin/dotutil
@@ -173,37 +173,42 @@ case "$# ${1:-}" in
     shift
     # list up app installers which are available
     # (no arguments)
-    cd "$DOTFILES_LOC/etc/dotutil/install" || exit 1
+
+    cd "$DOTFILES_LOC/etc/installer" || exit 1
     printf '%s\n' *
     ;;
   [!1]' install')
     shift
     # install app to the local app directory
     # $1~: the name of apps to install
+
     for scriptname in "$@"; do
-      [ -r "$DOTFILES_LOC/etc/dotutil/install/$scriptname" ] || { printf 'ERROR\n'; continue; }
-      sh "$DOTFILES_LOC/etc/dotutil/install/$scriptname"
+      [ -r "$DOTFILES_LOC/etc/installer/$scriptname" ] || { printf 'ERROR\n'; continue; }
+      sh "$DOTFILES_LOC/etc/installer/$scriptname"
     done
     ;;
   [!1]' uninstall')
     shift
     # remove app from the local app directory
     # $1~: the name of apps to uninstall
+
     for scriptname in "$@"; do
-      [ -r "$DOTFILES_LOC/etc/dotutil/uninstall/$scriptname" ] || { printf 'ERROR\n'; continue; }
-      sh "$DOTFILES_LOC/etc/dotutil/uninstall/$scriptname"
+      [ -r "$DOTFILES_LOC/etc/installer/$scriptname" ] || { printf 'ERROR\n'; continue; }
+      sh "$DOTFILES_LOC/etc/installer/$scriptname"  # (!todo!) implement an option to run as a uninstaller
     done
     ;;
   '2 newsh')
     shift
     # make a new command file from templates
     # $1: the path of a new sh file
+
     cp -f "$DOTFILES_LOC/etc/template/command.sh" "$1" || exit 1
     ;;
   '2 newfunc')
     shift
     # make a new function file from templates
     # $1: (optional) the path of a new sh file
+
     cp -f "$DOTFILES_LOC/etc/template/libfunc.sh" "${1:-./}"
     ;;
   '1 withdraw')
