refactor some scripts

diff --git a/bin/sln b/bin/sln
--- a/bin/sln
+++ b/bin/sln
@@ -1,49 +1,58 @@
 #!/bin/sh
-# >> parse_and_print_usage[description]
-# Short description here ...
-# ...
-# << parse_and_print_usage[description]
+# >> __description__
+# This command is an interactive filter to select lines by key-numbers.
+# <<
 
-################################################################
+
+######################################################################
 # preprocessing
-################################################################
+######################################################################
+
+
+# load library functions
+. "$DOTFILES_DIR/lib/init_env.sh"
+. "$DOTFILES_DIR/lib/parse_usage.sh"
+. "$DOTFILES_DIR/lib/log_error.sh"
+
 
 # initialize shell environment
-set -u
-umask 0022
-LC_ALL=C
-type command > /dev/null 2>&1 && type getconf > /dev/null 2>&1 &&
-PATH="$(command -p getconf PATH)${PATH+:}${PATH-}"
-UNIX_STD=2003
-export LC_ALL PATH UNIX_STD
+init_env
 
-# load and define functions
-#. "$DOTFILES_DIR/lib/log_error.sh"
 
-# catch signals
-#trap '' HUP INT QUIT TERM
+# parse options
+# s: switch, no need any values (ex. -s)
+# v: value, need to input some values (ex. -k abc)
+# o: optional, no need to specify (e.g. [-s])
+while :; do
+  case "${1:-}" in
+    -h|--help)  # >> __option__[so]:print out the usage to stderr
+      parse_usage
+      exit 0
+      ;;
+    --)  # >> __option__[so]
+      shift
+      break
+      ;;
+    -*)
+      log_error "invalid option: $1"
+      exit 1
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
-################################################################
-# argument parsing
-################################################################
 
-# print the usage and exit
-case "$# ${1:-}" in
-  '1 -h'|'1 --help')
-    #parse_and_print_usage
-    :
-    ;;
-esac
-
-################################################################
+######################################################################
 # main routine
-################################################################
-
-
-# slb - select lines by numbers
+######################################################################
 
 
 tmpfile=$(mktemp "/tmp/tmp.${0##*/}.XXXXXXXXXX")
+
+
+# catch signals
 trap 'rm -f '"$tmpfile"'' EXIT HUP INT QUIT TERM
 
 
@@ -70,7 +79,7 @@ while :; do
       break
     else
       # if the input is invalid, output message to stderr.
-      printf 'ERROR: invalid input: %s\n' "$prompt_input" >&2
+      log_error "invalid input: $prompt_input"
     fi
   fi
 done
diff --git a/bin/termcl b/bin/termcl
--- a/bin/termcl
+++ b/bin/termcl
@@ -1,57 +1,35 @@
 #!/bin/sh
+# >> __description__
+# This is a utility to print coloring text experimentally.
+# <<
 
-################################################################
-#
-# termcl
-#   - terminal color print
-#
-# written by raptowl on 2019/11/17
-#
-################################################################
 
-################################################################
+######################################################################
 # preprocessing
-################################################################
+######################################################################
 
-# initialize shell environment
-set -u
-umask 0022
-LC_ALL=C
-type command > /dev/null 2>&1 && type getconf > /dev/null 2>&1 &&
-PATH="$(command -p getconf PATH)${PATH+:}${PATH-}"
-UNIX_STD=2003
-export LC_ALL PATH UNIX_STD
 
-# load and define functions
+# load library functions
+. "$DOTFILES_DIR/lib/init_env.sh"
+. "$DOTFILES_DIR/lib/parse_usage.sh"
 . "$DOTFILES_DIR/lib/log_error.sh"
 
-usage() {
-  cat <<_EOT_ >&2
-Usage: ${0##*/} [-h | --help]
 
-${0##*/} is a utility to check the terminal color.
+# initialize shell environment
+init_env
 
-option:
-  -h | --help: print out the usage to stderr
-_EOT_
-  exit 1
-}
-
-################################################################
-# argument parsing
-################################################################
-
-# print the usage and exit
-case "$# ${1:-}" in
-  '1 -h'|'1 --help')
-    usage
-    ;;
-esac
 
 # parse options
+# s: switch, no need any values (ex. -s)
+# v: value, need to input some values (ex. -k abc)
+# o: optional, no need to specify (e.g. [-s])
 while :; do
   case "${1:-}" in
-    --)
+    -h|--help)  # >> __option__[so]:print out the usage to stderr
+      parse_usage
+      exit 0
+      ;;
+    --)  # >> __option__[so]
       shift
       break
       ;;
@@ -65,16 +43,24 @@ while :; do
   esac
 done
 
+
 if [ $# -ne 0 ]; then
-  log_error 'invalid arguments'
+  log_error "invalid arguments: $*"
   exit 1
 fi
 
-################################################################
+
+######################################################################
 # main routine
-################################################################
+######################################################################
+
+
+# catch signals
+#trap '' EXIT HUP INT QUIT TERM
+
 
 printf '             40m   41m   42m   43m   44m   45m   46m   47m \n' >&2
+
 
 printf '    m' >&2
 printf ' \033[0m gYw \033[0m' >&2
@@ -88,6 +74,7 @@ printf ' \033[46m gYw \033[0m'  >&2
 printf ' \033[47m gYw \033[0m'  >&2
 printf '\n' >&2
 
+
 printf '   1m' >&2
 printf ' \033[1m gYw \033[0m' >&2
 printf ' \033[1;40m gYw \033[0m' >&2
@@ -99,6 +86,7 @@ printf ' \033[1;45m gYw \033[0m' >&2
 printf ' \033[1;46m gYw \033[0m' >&2
 printf ' \033[1;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  30m' >&2
 printf ' \033[30m gYw \033[0m' >&2
@@ -112,6 +100,7 @@ printf ' \033[30;46m gYw \033[0m' >&2
 printf ' \033[30;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;30m' >&2
 printf ' \033[1;30m gYw \033[0m' >&2
 printf ' \033[1;30;40m gYw \033[0m' >&2
@@ -123,6 +112,7 @@ printf ' \033[1;30;45m gYw \033[0m' >&2
 printf ' \033[1;30;46m gYw \033[0m' >&2
 printf ' \033[1;30;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  31m' >&2
 printf ' \033[31m gYw \033[0m' >&2
@@ -136,6 +126,7 @@ printf ' \033[31;46m gYw \033[0m' >&2
 printf ' \033[31;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;31m' >&2
 printf ' \033[1;31m gYw \033[0m' >&2
 printf ' \033[1;31;40m gYw \033[0m' >&2
@@ -147,6 +138,7 @@ printf ' \033[1;31;45m gYw \033[0m' >&2
 printf ' \033[1;31;46m gYw \033[0m' >&2
 printf ' \033[1;31;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  32m' >&2
 printf ' \033[32m gYw \033[0m' >&2
@@ -160,6 +152,7 @@ printf ' \033[32;46m gYw \033[0m' >&2
 printf ' \033[32;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;32m' >&2
 printf ' \033[1;32m gYw \033[0m' >&2
 printf ' \033[1;32;40m gYw \033[0m' >&2
@@ -171,6 +164,7 @@ printf ' \033[1;32;45m gYw \033[0m' >&2
 printf ' \033[1;32;46m gYw \033[0m' >&2
 printf ' \033[1;32;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  33m' >&2
 printf ' \033[33m gYw \033[0m' >&2
@@ -184,6 +178,7 @@ printf ' \033[33;46m gYw \033[0m' >&2
 printf ' \033[33;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;33m' >&2
 printf ' \033[1;33m gYw \033[0m' >&2
 printf ' \033[1;33;40m gYw \033[0m' >&2
@@ -195,6 +190,7 @@ printf ' \033[1;33;45m gYw \033[0m' >&2
 printf ' \033[1;33;46m gYw \033[0m' >&2
 printf ' \033[1;33;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  34m' >&2
 printf ' \033[34m gYw \033[0m' >&2
@@ -208,6 +204,7 @@ printf ' \033[34;46m gYw \033[0m' >&2
 printf ' \033[34;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;34m' >&2
 printf ' \033[1;34m gYw \033[0m' >&2
 printf ' \033[1;34;40m gYw \033[0m' >&2
@@ -219,6 +216,7 @@ printf ' \033[1;34;45m gYw \033[0m' >&2
 printf ' \033[1;34;46m gYw \033[0m' >&2
 printf ' \033[1;34;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  35m' >&2
 printf ' \033[35m gYw \033[0m' >&2
@@ -232,6 +230,7 @@ printf ' \033[35;46m gYw \033[0m' >&2
 printf ' \033[35;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;35m' >&2
 printf ' \033[1;35m gYw \033[0m' >&2
 printf ' \033[1;35;40m gYw \033[0m' >&2
@@ -243,6 +242,7 @@ printf ' \033[1;35;45m gYw \033[0m' >&2
 printf ' \033[1;35;46m gYw \033[0m' >&2
 printf ' \033[1;35;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  36m' >&2
 printf ' \033[36m gYw \033[0m' >&2
@@ -256,6 +256,7 @@ printf ' \033[36;46m gYw \033[0m' >&2
 printf ' \033[36;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;36m' >&2
 printf ' \033[1;36m gYw \033[0m' >&2
 printf ' \033[1;36;40m gYw \033[0m' >&2
@@ -267,6 +268,7 @@ printf ' \033[1;36;45m gYw \033[0m' >&2
 printf ' \033[1;36;46m gYw \033[0m' >&2
 printf ' \033[1;36;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 printf '  37m' >&2
 printf ' \033[37m gYw \033[0m' >&2
@@ -280,6 +282,7 @@ printf ' \033[37;46m gYw \033[0m' >&2
 printf ' \033[37;47m gYw \033[0m' >&2
 printf '\n' >&2
 
+
 printf '1;37m' >&2
 printf ' \033[1;37m gYw \033[0m' >&2
 printf ' \033[1;37;40m gYw \033[0m' >&2
@@ -291,5 +294,6 @@ printf ' \033[1;37;45m gYw \033[0m' >&2
 printf ' \033[1;37;46m gYw \033[0m' >&2
 printf ' \033[1;37;47m gYw \033[0m' >&2
 printf '\n' >&2
+
 
 exit 0
